<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Version>0.0.1</Version>
    <Authors>Kilfour</Authors>
    <PackageId>QuickPersistr.EntityFrameworkCore.PostgreSql</PackageId>
    <Title>QuickPersistr adapter for EF Core PostgreSQL</Title>
    <Description>Isolated temporary PostgreSQL database scope for QuickPersistr and Entity Framework Core.</Description>
    <PackageTags>property-based-testing;persistence;testing;database;entity-framework-core;postgresql;npgsql</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/kilfour/QuickPersistr</RepositoryUrl>
    <PackageProjectUrl>https://github.com/kilfour/QuickPersistr</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="[8.0.10,9.0.0)" />
    <ProjectReference Include="..\QuickPersistr.EntityFrameworkCore\QuickPersistr.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
