<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Version>0.0.1</Version>
    <Authors>Kilfour</Authors>

    <PackageId>QuickPersistr</PackageId>
    <Title>QuickPersistr</Title>
    <Description>Property-based persistence testing for .NET.</Description>
    <PackageTags>property-based-testing;persistence;testing;database;QuickCheckr</PackageTags>

    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/kilfour/QuickPersistr</RepositoryUrl>
    <RepositoryBranch>main</RepositoryBranch>
    <PackageProjectUrl>https://github.com/kilfour/QuickPersistr</PackageProjectUrl>

    <!-- NuGet metadata -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>

    <!-- Docs -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>

    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuickCheckr" Version="0.2.3" />
  </ItemGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\QuickCheckr\QuickCheckr\QuickCheckr.csproj" /> -->
  </ItemGroup>

</Project>
